### ISSUE TITLE
Missing endpoints `/api/v1/set_colour` and `/api/v1/set_brightness`

### ISSUE THREAD

**Issue by jerome3o** [Samueljbk/yeelight_server#14]
The FE has buttons for setting brightness since [this pr](https://github.com/Samueljbk/yeelight_server/pull/13)

Can you please add in endpoints as documented [here](https://github.com/Samueljbk/yeelight_server/blob/main/docs/demo_app.md#description)

**Comment by Samueljbk** [comment]
Implemented brightness - https://github.com/Samueljbk/yeelight_server/pull/16

Working on set_colour now

**Comment by Samueljbk** [comment]
Implemented set_colour - https://github.com/Samueljbk/yeelight_server/pull/17
